version: '3'
services:
  frontend:
    build: frontend
    networks:
      - my-network

  backend:
    build: backend
    networks:
      - my-network

  nginx:
    container_name: nginx_server
    build:
      context: ./nginx/.
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - frontend
      - backend

networks:
  my-network:
    driver: bridge
